CREATE DATABASE DB_RiyanRattan;

USE DB_RiyanRattan;

CREATE TABLE VENDOR  (
	V_CODE  	int				NOT NULL,
	V_NAME		varchar(30) 	NOT NULL,
	V_CONTACT	varchar(50) 	NOT NULL,
	V_AREACODE 	char(3) 		NOT NULL,
	V_PHONE		char(8) 		NOT NULL,
	V_STATE		char(2) 		NOT NULL,
	V_ORDER 	char(1) 		NOT NULL,
	CONSTRAINT	VENDOR_PK		PRIMARY KEY (V_CODE)
);

CREATE TABLE PRODUCT (
	P_CODE		varchar(10) 	NOT NULL,
	P_DESCRIPT	varchar(35)		NOT NULL,
	P_INDATE	datetime		NOT NULL,
	P_QOH		smallint 		NOT NULL,
	P_MIN		smallint		NOT NULL,
	P_PRICE		decimal(8,2)	NOT NULL,
	P_DISCOUNT	decimal(5,2)	NOT NULL,
	V_CODE		int				NOT NULL,
	CONSTRAINT	PRODUCT_PK	PRIMARY KEY (P_CODE),
	CONSTRAINT	PRODUCT_FK 	FOREIGN KEY (V_CODE)		REFERENCES	VENDOR(V_CODE)
		ON UPDATE CASCADE   
		ON DELETE NO ACTION
        
);
